apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom
  labels:
    app: custom
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: registry.redhat.io/rhel8/httpd-24
        ports:
        - containerPort: 8080
      - name: database
        image: registry.redhat.io/rhel8/mysql-80:1
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_USER
          value: user1
        - name: MYSQL_DATABASE
          value: items
        - name: MYSQL_PASSWORD
          value: mypa55
        - name: MYSQL_ROOT_PASSWORD
          value: r00tpa55

--- 
apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    app: custom

spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: web
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: myroute

spec:
  to:
    kind: Service
    name: myservice
